


# AVANCE

# Sitio para recordar por donde quede en el curso 

# 3.8





# Tema	Qué aprender o practicar
# enumerate()	Para recorrer listas con índice.
# zip()	Para recorrer varias listas a la vez.
# map() y filter()	Alternativas a list comprehensions.
# Diccionarios por comprensión	{k: v for ...} para construir diccionarios dinámicos.
# Funciones (def)	Encapsular tu lógica para reutilizarla.
# Módulos útiles (random, math)	Para extender tus scripts con cosas prácticas.
# dominar operadores bit a bit